### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by ZhuYanzhen1** [xu7wong/openocd_wchlink#1]
源码中的子仓库[submodule "jimtcl"]缺少重要构建文件configure，从https://github.com/msteveb/jimtcl.git拉最新的仓库下来替换后编译出的openocd程序会崩溃。
编译环境：msys2 mingw64

**Comment by xu7wong** [comment]
本项目目前仅在MAC OS下测试过，windows下MounRiver已经有完整解决方案。
